// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://emsuybvkjowipxjddctm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVtc3V5YnZram93aXB4amRkY3RtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcyNjgzNjQsImV4cCI6MjA1Mjg0NDM2NH0.7Hfk5xbWWss30jSrgEfI53KGZV37NjSLB5Km43cqg-0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);